"""Per-character video feed identity for the OBS integration.

A character gets a VDO.ninja stream id (generated by ScenePlay, so the player
never types a URL) and an optional custom feed URL for people running their
own capture setup. OBS loads the matching view URL in a browser source.

Additive columns only — guarded so re-runs and pre-TTRPG databases are safe.

Revision ID: 0007_obs_video_feed
Revises: 0006_session_notes
Create Date: 2026-07-30
"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0007_obs_video_feed'
down_revision = '0006_session_notes'
branch_labels = None
depends_on = None


def _columns(bind, table):
    """Column names of `table`, or [] if the table doesn't exist."""
    return [r[1] for r in bind.exec_driver_sql(f'PRAGMA table_info("{table}")')]


def upgrade():
    bind = op.get_bind()

    def add_column(table, column, decl):
        cols = _columns(bind, table)
        if cols and column not in cols:
            bind.exec_driver_sql(f'ALTER TABLE {table} ADD COLUMN {column} {decl}')

    add_column('tblCharacters', 'video_stream_id', "TEXT DEFAULT ''")
    add_column('tblCharacters', 'video_feed_url',  "TEXT DEFAULT ''")


def downgrade():
    # SQLite column drops mean a full table rebuild and these are additive
    # with empty defaults — nothing reads them when the feature is off.
    pass
